### ISSUE TITLE
WARNING  Failed to get latest APK version!

### ISSUE THREAD

**Issue by Clarksonfan** [Der-Henning/tgtg#131]
When running the Windows prebuild release version 1.11.1 I get the following warning upon startup:

WARNING  Failed to get latest APK version!

Not sure if this effects the running of the program or not, but have had several telegram notifications time out and not go through today, but the gmail notifications seem to work.

**Comment by Der-Henning** [comment]
Hi @Clarksonfan.
Thank you for the Feedback.
The Error causing the Warning is fixed with [251a72b](https://github.com/Der-Henning/tgtg/commit/251a72b2ab9220fed7bc3d8433cebccdeb76f434). The latest release v1.11.2 now contains this fix.

The telegram connector is configured to use a 60 seconds timeout. If these timeouts appear you probably have a bad internet connection / connection to the telegram servers.
You can check the connection and response time with 
``ping api.telegram.org``
or
``traceroute api.telegram.org``

**Comment by Clarksonfan** [comment]
Thanks  @Der-Henning  downloaded the latest release and no longer get that error.

Still getting the following error on telegram randomly (maybe once every 10 notifications)

2022-08-21 12:37:51 ERROR    Telegram Error: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by Der-Henning** [comment]
You are welcome. 
The Error you are seeing is not critical and gets handled by the script. I will change it to a WARNING with the next release.

I close this issue since it seems to be resolved. Feel free to reopen or create new issues if needed.
